### ISSUE TITLE
Issue when no guess submitted in time

### ISSUE THREAD

**Issue by josepablocam** [danielwang5/Color#13]
Simulating with: iPhone 7 Plus

When there is no guess provided within the time limit, you should record an appropriate timeout action for the logs and move on to the next plate. In the current version, it hits a call to `abort()`

**Comment by josepablocam** [comment]
It seems this issue only arises when you: 1) first guess at least one plate correctly, and then 2) don't submit a guess at all for a plate

**Comment by danielwang5** [comment]
fixed i think?

**Comment by josepablocam** [comment]
@danielwang5 seems fairly easy to check that the fix works, so if possible, just give it a quick check
