### ISSUE TITLE
Break out counter for correct vs incorrect count of plates

### ISSUE THREAD

**Issue by josepablocam** [danielwang5/Color#15]
Currently, it seems the counter is only for correct. I think users would like to see both

**Comment by josepablocam** [comment]
I'm re-opening this. Users shouldn't have to guess that the left hand side of the `/` are correct and the others are incorrect. See below for example.

I would make this:

```
0 Correct
0 Incorrect
```
and increment counters appropriately, or something along those lines.

![image](https://user-images.githubusercontent.com/5097108/28472674-7a2ffd9c-6e0f-11e7-9331-aac9b319c8a2.png)

**Comment by danielwang5** [comment]
fixed Into "4 Correct / 2 Incorrect"
